### PR TITLE
generate 3d printable Enclosure

### PR DESCRIPTION
**Pull request by generationmake**

### CODE REVIEW

**Comment by generationmake** [comment]
@aentinger
please check

**Comment by aentinger** [comment]
Please add me as collaborator to this project :pray:

**Comment by aentinger** [comment]
Thanks for adding me, I wanted to change the base of this PR ;)

**Comment by aentinger** [comment]
Test print in progress ...

**Comment by aentinger** [comment]
I've completed the test print and it fits nicely! Good work!

IMG_20230503_044741_964
IMG_20230502_190009_301

**Review by aentinger — APPROVED** [review]
LGTM 👍

**Comment by aentinger** [comment]
Maybe make the opening for the USB a bit wider, like for the OpenCyphalPicoBase case. Otherwise it might get tight to plug a USB cable in there.

**Pull request merged**
