### PR TITLE
Rev 0.1

### PR DESCRIPTION
**Pull request by generationmake**
prototype release

### CODE REVIEW

**Comment by generationmake** [comment]
@aentinger :
comments please ;-)

**Comment by aentinger** [comment]
Good Morning @generationmake ☕ 👋 

Thank you for all your work you invested into this design :bow:.

Here are a couple of questions that came up on my end when reviewing the schematic:
* The voltage divider for `MEAS_CANVCC` can be probably lower than 1/11. `CANVCC` is likely to be around 5V, if V,ADC,IN,MAX is around 3V3 than dividing by 2 (or 3 as a safety margin) should be sufficient.
* The same is true for `MEAS_5V`.
* What's the purpose of the 5V net? Looking at the schematic I really don't get why its there 🤔 .

**Comment by aentinger** [comment]
Would it make sense to add some tantalum condensators with very low ESR to buffer current spikes during servo actuation?

**Comment by generationmake** [comment]
hi @aentinger I added two additional ceramic capacitors on VCC. This should handle the current peaks from servos. There is not much space left for additional capacitors.

**Comment by aentinger** [comment]
>hi @aentinger I added two additional ceramic capacitors on VCC.

Great! 👍 Perhaps you can export a new schematic, so I can take another look at some time 😉

**Comment by aentinger** [comment]
Voltage dividers have been fixed, still not sure about the purpose of the 5V net :wink:

**Comment by aentinger** [comment]
Hi @generationmake :coffee: :wave: any updates on the voltage issue?

**Comment by generationmake** [comment]
hi @aentinger 
i have made several tests and checks and it seems to be a soldering issue.
It seems like the RAA211650 is not so easy to solder.
we will have to resolder your board.

**Comment by aentinger** [comment]
Great news! Can you give your fixed Version to @wuehr1999 on Wednesday? Thursday afternoon I'll give you my version then for a swap.

**Pull request merged**
